name: Main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: 22
          distribution: 'temurin'
          cache: maven

      - name: Build
        run: mvn clean install -DskipTests

      - name: Run ojp-server
        run: mvn verify -pl ojp-server -Prun-ojp-server > ojp-server.log 2>&1 &

      - name: Run tests
        run: mvn test -DdisablePostgresTests