/**
 * Translation helpers between the SQL text TypeORM's `SqlServerQueryRunner` generates and
 * what `OjpClient` (ultimately, a JDBC `PreparedStatement` on the ojp-server) expects.
 *
 * `SqlServerDriver.escapeQueryWithParameters()`/`createParameter()` always emit `@0, @1, @2,
 * ...` (zero-based, index-based) placeholders. `OjpClient` speaks plain JDBC: `?` placeholders
 * bound strictly by occurrence order. As with the Postgres shim's `$1, $2, ...` translation,
 * the two conventions are NOT equivalent when the same parameter index is referenced more than
 * once in a statement — `?` must be repeated once per occurrence, with the matching value
 * duplicated in the parameter array, since JDBC binds positionally by occurrence, not by
 * referenced index.
 */

const MSSQL_PARAM_PATTERN = /@(\d+)\b/g;

export interface TranslatedQuery {
  sql: string;
  params: unknown[];
}

/** Rewrites `@0, @1, ...` placeholders into `?`, reordering/duplicating `params` (0-based) as needed. */
export function translateIndexedParams(sql: string, params: ReadonlyArray<unknown> = []): TranslatedQuery {
  const orderedParams: unknown[] = [];
  const translatedSql = sql.replace(MSSQL_PARAM_PATTERN, (_match, indexStr: string) => {
    orderedParams.push(params[Number(indexStr)]);
    return '?';
  });
  return { sql: translatedSql, params: orderedParams };
}

/**
 * Splits a T-SQL batch into individual statements on top-level `;`, ignoring semicolons
 * inside single-quoted string literals. TypeORM's `InsertQueryBuilder`/`UpdateQueryBuilder`
 * send exactly this kind of batch for mssql when returning generated columns:
 * `DECLARE @OutputTable TABLE (...); INSERT INTO ... OUTPUT INSERTED.col INTO @OutputTable
 * VALUES (...); SELECT * FROM @OutputTable`.
 */
function splitBatchStatements(sql: string): string[] {
  const statements: string[] = [];
  let current = '';
  let inString = false;
  for (let i = 0; i < sql.length; i += 1) {
    const ch = sql[i];
    if (ch === '\'') {
      inString = !inString;
      current += ch;
      continue;
    }
    if (ch === ';' && !inString) {
      statements.push(current);
      current = '';
      continue;
    }
    current += ch;
  }
  if (current.trim().length > 0) {
    statements.push(current);
  }
  return statements;
}

const RESULT_SET_LEADING_KEYWORDS = /^\s*(SELECT|WITH)\b/i;
const HAS_OUTPUT_CLAUSE = /\bOUTPUT\b/i;
// Real T-SQL always separates OUTPUT from its INTO target with a column list
// (`OUTPUT INSERTED.col1, INSERTED.col2 INTO @table`), so INTO is never adjacent to OUTPUT —
// it must be searched for anywhere later in the statement, not immediately after it.
const HAS_OUTPUT_INTO_TARGET = /\bOUTPUT\b[\s\S]*?\bINTO\b/i;

/** True for an `OUTPUT` clause with no `INTO` target, i.e. one that returns its rows directly. */
function hasBareOutputClause(sql: string): boolean {
  return HAS_OUTPUT_CLAUSE.test(sql) && !HAS_OUTPUT_INTO_TARGET.test(sql);
}

/**
 * Decides whether a statement (or multi-statement batch) produces a JDBC `ResultSet` (must go
 * through `OjpClient.executeQuery`) or only an affected-row count (`OjpClient.executeUpdate`).
 *
 * Covers three shapes generated by `SqlServerQueryRunner`/the mssql query builders:
 *  - Plain `SELECT`/`WITH` statements.
 *  - `INSERT`/`UPDATE ... OUTPUT INSERTED.col INTO @OutputTable; SELECT * FROM @OutputTable`
 *    batches used to read back generated columns — the batch's LAST statement is the one
 *    that actually yields rows, so it (not the whole batch text) decides this.
 *  - `DELETE ... OUTPUT DELETED.col WHERE ...` (no `INTO`, so the DELETE statement itself
 *    returns the rows directly).
 */
export function producesResultSet(sql: string): boolean {
  const statements = splitBatchStatements(sql);
  const lastStatement = statements[statements.length - 1] ?? sql;
  if (RESULT_SET_LEADING_KEYWORDS.test(lastStatement)) {
    return true;
  }
  return hasBareOutputClause(sql);
}

const COMMAND_PATTERN = /^\s*([A-Za-z]+)/;

/** Extracts the leading SQL verb (`SELECT`, `INSERT`, `DECLARE`, ...), mirroring `mssql`'s implicit `queryType` detection. */
export function detectCommand(sql: string): string {
  const match = COMMAND_PATTERN.exec(sql);
  return match ? match[1].toUpperCase() : '';
}
